---
title: "**Data Science Tutorials**"
author: '[Iain Carmichael](https://github.com/idc9)'
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
---


This page contains a number of introduction to data science tutorials and a list of resources that I've found helpful to learn data science.


# **R**


The (free) [R for Data Science](http://r4ds.had.co.nz/) by Hadley Wickham is a fantastic resource to learn R.

If you are brand new to R [**see this page to get started**](R/new_to_R.html).

## Exercises


[**Viz + subsetting**](R/movies_viz_subsetting.html) 

Practice data manipulation and plotting with `dplyr` and `ggplot`. If you are familiar with base R these will be helpful to learn the [tidyverse](http://tidyverse.org/). 

[**Analyze UNC deparments**](https://idc9.github.io/stor390/assignments/unc_depts/unc_depts.html) (more viz + subsetting).


[**Modeling + more viz**](R/movies_modeling.html) 

Practice fitting machine learning models and visualizing high-dimensional data.



## Resources

[**R for Data Science**](http://r4ds.had.co.nz/)


The [**JHU data science specialization**](https://www.coursera.org/specializations/jhu-data-science) on Coursera is a good crash course in R.

# **Python**

If you are new to Python and have some previous programming experience I suggest going through [Google's Python class](https://developers.google.com/edu/python/) to get started with Python. Spend a couple hours working through the class until you get the hang of it. Then download [Anaconda](https://www.continuum.io/downloads) which has most of the stats/machine learning Python packages you'll need. It also comes with [Jupyter notebook](http://jupyter.org/) (formerly iPython) which you should use for data science projects. *Warning*: both Python 2 and 3 are commonly used.


## Exercises

[**Viz + subsetting**](Python/movies_viz_subsetting.html) 

Practice data manipulation and plotting with `pandas` and `matplotlib`.


[**Modeling + more viz**](Python/movies_modeling.html) 

Practice fitting machine learning models and visualizing high-dimensional data with `sklearn` and `statsmodels`.

## Resources

[**Chris Albon's website**](http://chrisalbon.com/) (great for a lot of things, particularly for pandas)

[**Python for Data Science**](http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb) as a Jupyter notebook


[**Computational Statistics**](http://people.duke.edu/~ccc14/sta-663-2016/index.html)


# **Other resources**

[**Introduction to Statistical Learning with Applications in R**](http://www-bcf.usc.edu/~gareth/ISL/) is a fantastics textbook.

[This google doc](https://docs.google.com/document/d/18gBqIGNyOqzqygRjFAIA7jnieXRVMtBc2_yL7UD-3TM/edit?usp=sharing) contains a list of my favorite statistics/machine learning/data science resources (most are free online).



# **Acknowledgements**

A number of people helped created these tutorials including

- [Ethan Koch](https://www.linkedin.com/in/ethan-koch-25668b113/)
- [Wenyue Liu](https://www.linkedin.com/in/bismarckliu/)
- [Nikhil Prasad](https://www.linkedin.com/in/globmont/)
- [Mine Cetinkaya-Rundel](http://www2.stat.duke.edu/~mc301/) generously provided the *movies.csv* data set.

